FROM apache/superset:1.4.0

USER root

RUN apt update && apt install -y gettext-base
RUN pip install gevent gunicorn psycopg2-binary sqlalchemy-redshift

COPY run.sh .

USER superset

ENTRYPOINT ["bash"]

CMD ["run.sh"]
